<a href="https://colab.research.google.com/github/pinkdolphin11/ESAA/blob/main/3_14_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Chap 1. 파이썬 기반의 머신러닝과 생태계 이해**

1. 머신러닝의 개념

  머신러닝 : 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

  머신러닝은 데이터를 기반으로 숨겨진 패턴을 인지한다. 데이터 분석 영역은 재빠르게 머신러닝 기반의 예측 분석으로 재편되고 있다.

  [머신러닝의 분류]

  1) 지도학습(Supervised Learning)
  *   분류(Classification)
  *   회귀(Regression)
  *   추천 시스템
  *   시각/음성 감지/인지
  *   텍스트 분석, NLP

  2) 비지도학습(Un-supervised Learning)

  *   클러스터링
  *   차원 축소
  *   강화학습(Reinforcement Learning)

  [데이터 전쟁]

  머신러닝 기술이 발전함에 따라 데이터의 중요성이 강조되고 있다. 좋은 품질의 데이터를 갖추지 못하면 머신러닝의 수행 결과도 좋을 수 없다.(Garbage in, garbage out.)


2. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

  * 머신러닝 패키지 : 사이킷런(Scikit-Learn)
  * 행렬/선형대수/통계 패키지 : 넘파이(NumPy), 사이파이(SciPy)
  * 데이터 핸들링 : 판다스
  * 시각화 : 맷플롯립(MatPlotlib), 시본(Seaborn)

















> [파이썬 머신러닝을 위한 S/W 설치]







In [ ]:
import numpy
import pandas
import matplotlib.pyplot
import seaborn
from sklearn.model_selection import train_test_split

3. 넘파이

  넘파이(NumPy, Numerical Python) : 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지. 배열 기반의 연산은 물론이고 다양한 데이터 핸들링 기능을 제공한다.



> [넘파이 ndarray 개요]



In [ ]:
import numpy as np

  넘파이 array() 함수는 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환한다. 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 형태로 가지고 있다.

In [ ]:
array1=np.array([1,2,3])
print("array1 type:", type(array1))
print("array1 array 형태:", array1.shape)

array2=np.array([[1,2,3],[2,3,4]])
print("array2 type:", type(array2))
print("array2 array 형태:", array2.shape)

array3=np.array([[1,2,3]])
print("array3 type:", type(array3))
print("array3 array 형태:", array3.shape)

print("array1: {:0}차원, array2: {:1}차원, array3: {:2}차원".format(array1.ndim, array2.ndim, array3.ndim))

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)
array1: 1차원, array2: 2차원, array3:  2차원




> [ndarray의 데이터 타입]



ndarray 내의 데이터 값은 숫자, 문자열, 불 값 등이 모두 가능하다. ndarray 내의 데이터 타입은 연산의 특성상 같은 데이터 타입만 가능하다. ndarray 내의 데이터 타입은 dtype 속성으로 확인할 수 있다. 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

In [ ]:
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

list2=[1,2,"test"]
array2=np.array(list2)
print(array2, array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3, array3.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64
['1' '2' 'test'] <U21
[1. 2. 3.] float64


astype() 메서드를 이용해 ndarray 내 데이터값의 타입을 변경할 수 있다. astype()에 인자로 원하는 타입을 문자열로 지정하면 된다.

In [ ]:
array_int=np.array([1,2,3])
array_float=array_int.astype("float64")
print(array_float, array_float.dtype)

array_int1=array_float.astype("int32")
print(array_int1, array_int1.dtype)

array_float1=np.array([1.1, 2.1, 3.1])
array_int2=array_float1.astype("int32")
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32




> [ndarray를 편리하게 생성하기 - arange, zeros, ones]



특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 경우 arange(), zeros(), ones() 이용

1) arange

  default 함수 인자는 stop 값이며, 0부터 stop 값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray를 만든다.


In [ ]:
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


2) zeros, ones

튜플 형태의 shape 값을 입력하면 모든 값을 0/1으로 채운 해당 shape를 가진 ndarray 반환

In [ ]:
zero_array=np.zeros((3,2),dtype="int32")
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)




> [ndarray의 차원과 크기를 변경하는 reshape()]



In [ ]:
array1=np.arange(10)
print("array1:\n",array1)

array2=array1.reshape(2,5)
print("array2:\n",array2)

array3=array1.reshape(5,2)
print("array3:\n",array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


-1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환한다.

In [ ]:
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print("array2 shape:", array2.shape)
array3=array1.reshape(5,-1)
print("array3 shape:", array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다.

In [ ]:
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print("array3d:\n",array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print("array5:\n",array5.tolist())
print("array5 shape:",array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print("array6:\n",array6.tolist())
print("array6 shape:",array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)




> [넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)]

1) 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터 반환

2) 슬라이싱(Slicing) : 연속된 인덱스상의 ndarray 추출

3) 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray 반환

4) 불린 인덱싱(Boolean Indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray 반환



<단일 값 추출>

In [ ]:
#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(start=1,stop=10)
print("array1:",array1)
#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value=array1[2]
print("value:",value)
print(type(value))

print("맨 뒤의 값:", array1[-1], "맨 뒤에서 두 번째 값:",array1[-2])

array1[0]=9
array1[8]=0
print("array1:",array1)

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8
array1: [9 2 3 4 5 6 7 8 0]


In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print("(row=0, col=0) index 가리키는 값:",array2d[0,0])
print("(row=0, col=1) index 가리키는 값:",array2d[0,1])
print("(row=1, col=0) index 가리키는 값:",array2d[1,0])
print("(row=2, col=2) index 가리키는 값:",array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


<슬라이싱>

In [ ]:
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


* ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주
* ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
* ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주





In [ ]:
array1=np.arange(start=1, stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print("array2d:\n", array2d)

print("array2d[0:2,0:2]\n", array2d[0:2,0:2])
print("array2d[1:3,0:3]\n", array2d[1:3,0:3])
print("array2d[1:3,:]\n", array2d[1:3,:])
print("array2d[:,:]\n", array2d[:,:])
print("array2d[:2,1:]\n", array2d[:2,1:])
print("array2d[:2,0]\n", array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print("array2d[0] shape:", array2d[0].shape, "array2d[1] shape:", array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


<팬시 인덱싱>

In [ ]:
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print("array2d[[0,1],2] => ",array3.tolist())

array4=array2d[[0,1],0:2]
print("array2d[[0,1],0:2] => ",array4.tolist())

array5=array2d[[0,1]]
print("array2d[[0,1]] => ",array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


<불린 인덱싱>

1) array1d>5와 같이 ndarray의 필터링 조건을 [] 안에 기재

2) False 값은 무시하고 True 값에 해당하는 인덱스값만 저장(유의해야 할 사항 : True값 자체인 1을 저장하는 것이 아니라 True값을 가진 인덱스를 저장)

3) 저장된 인덱스 데이터 세트로 ndarray 조회

In [ ]:
array1d=np.arange(start=1,stop=10)
# [ ] 안에 array1d>5 Boolean indexing 적용
array3=array1d[array1d>5]
print("array1d>5 불린 인덱싱 결과 값 :",array3)

array1d>5

boolean_indexes=np.array([False, False, False, False, False, True, True, True, True])
array3=array1d[boolean_indexes]
print("불린 인덱스로 필터링 결과 :",array3)

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print("일반 인덱스로 필터링 결과:", array4)

array1d>5 불린 인덱싱 결과 값 : [6 7 8 9]
불린 인덱스로 필터링 결과 : [6 7 8 9]
일반 인덱스로 필터링 결과: [6 7 8 9]




> [행렬의 정렬 - sort()와 argsort()]



<행렬 정렬>

1) np.sort() : 넘파이에서 sort()를 호출하는 방식. 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬 반환

2) ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식. 원 행렬 자체를 정렬한 형태로 반환하며 반환 값은 None


In [ ]:
org_array=np.array([3,1,9,5])
print("원본 행렬:", org_array)
# np.sort()로 정렬
sort_array1=np.sort(org_array)
print("np.sort() 호출 후 반환된 정렬 행렬:", sort_array1)
print("np.sort() 호출 후 원본 행렬:", org_array)
# ndarray.sort()로 정렬
sort_array2=org_array.sort()
print("org_array.sort( ) 호출 후 반환된 행렬:", sort_array2)
print("org_array.sort( ) 호출 후 원본 행렬:", org_array)

sort_array1_desc=np.sort(org_array)[::-1]
print("내림차순으로 정렬:", sort_array1_desc)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]
내림차순으로 정렬: [9 5 3 1]


In [ ]:
array2d=np.array([[8,12],[7,1]])
sort_array2d_axis0=np.sort(array2d,axis=0)
print("로우 방향으로 정렬:\n", sort_array2d_axis0)
sort_array2d_axis1=np.sort(array2d,axis=1)
print("칼럼 방향으로 정렬:\n", sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


<정렬된 행렬의 인덱스를 반환하기>

np.argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형태로 반환


In [ ]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print("행렬 정렬 시 원본 행렬의 인덱스:", sort_indices)

org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스:", sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
name_array=np.array(["John","Mike","Sarah","Kate","Samuel"])
score_array=np.array([78,95,84,98,88])
sort_indices_asc=np.argsort(score_array)
print("성적 오름차순 정렬 시 score_array의 인덱스:", sort_indices_asc)
print("성적 오름차순으로 name_array의 이름 출력:", name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']




> [선형대수 연산 - 행렬 내적과 전치 행렬 구하기]


<행렬 내적(행렬 곱)>

두 행렬 A와 B의 내적(곱)은 np.dot()으로 계산. 왼쪽 행렬의 로우(행)와 오른쪽 행렬의 칼럼(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값이므로 왼쪽 행렬의 열 개수=오른쪽 행렬의 열 개수일 때 연산 가능

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8],[9,10],[11,12]])
dot_product=np.dot(A,B)
print("행렬 내적 결과:\n",dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


<전치 행렬>

원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬

In [ ]:
A=np.array([[1,2],[3,4]])
transpose_mat=np.transpose(A)
print("A의 전치 행렬:\n",transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
